CREATE TABLE SYUSR (
   SYUSR_PK INTEGER NOT NULL,
   USRID VARCHAR2(30) NOT NULL,
   USRNAME VARCHAR2(50) NOT NULL,
   EMAIL VARCHAR2(100) NOT NULL,
   PW VARCHAR2(20),
   ACTIVE_YN VARCHAR2(1),
   EXPDT DATE,
   LOCK_YN  VARCHAR2(1),
   ADMIN_YN VARCHAR2(1),
   STUDENT_YN VARCHAR2(1),
   PRIMARY KEY (SYUSR_PK),
   UNIQUE (USRID),
   UNIQUE (EMAIL)
);