CREATE OR REPLACE TRIGGER TRG_GENERATE_SYUSR_PK
BEFORE INSERT OR UPDATE ON SYUSR
FOR EACH ROW
BEGIN
  IF :NEW.SYUSR_PK IS NULL THEN
    SELECT SQ_SYUSR_PK.NEXTVAL INTO :NEW.SYUSR_PK FROM DUAL;
  END IF;
END;